#+TITLE:WaveVib - An OCTAVE/MATLAB Toolbox for Wave-Based Modeling of Nonlinear Jointed Structures
#+INFOJS_OPT: view:overview mouse:pink sdepth:1 buttons:nil
#+BIBLIOGRAPHY: wavevib_docs.bib
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
# #+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.gnu.org/software/emacs/manual.css">

* Introduction
WaveVib is intended to be a set of OCTAVE/MATLAB routines that can be used to study wave-based linear and nonlinear structures. The main advantage with using this approach comes from the fact that the linear portions of the problem are represented without any approximation (unlike weighted residual or variational approaches). The interface supports both periodic as well as quasi-periodic steady state response regimes. Immediate use cases include jointed beams, trusses, frame structures, fluid-filled columns, rotordynamics, etc.

A good starting place for the new user to the Wave-Based Modeling (WBM) framework &/or this package are the papers [cite:@balajiWavebasedAnalysisJointed2022;@balajiWavebasedAnalysisJointed2023], upon which most of the rudiments of this package are based.
#+begin_details "The different folders in the repository are," :title-color "blue" :background-color "white"
1. blue:DEVEL\_PER [Obsolete]
   
  Contains development scripts used for development of the periodic response routines & examples.
2. blue:DEVEL\_QPER
   
  Contains development scripts used for development of the quasi-periodic response routines & examples. 
3. blue:EXAMPLES
   
   Contians examples with most of the core functionality
4. blue:REPS
   
   Contains miscellaneous reports (under REPn folders) and this main documentation (under the DOCS folder)
5. blue:ROUTINES
   
   Contains the core routines of the package.
#+end_details
* Programming Interface
* Examples
* Desirable Features [0/6]
1. [ ] 3D frame joint constitutions
2. [ ] EPMC Implementation
3. [ ] Joints connecting multiple pieces
4. [ ] More detailed examples
5. [ ] Stability Implementation
6. [ ] Quasi-Periodic Calculations
* References
#+CITE_EXPORT: csl ieee.csl
#+PRINT_BIBLIOGRAPHY: References


#+BEGIN_EXPORT html
<script type="text/javascript" src="./collcont_clkbls.js"></script>
#+END_EXPORT
